<?php
declare(strict_types=1);

defined('TYPO3') or die('Access denied.');

use TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider;
use TYPO3\CMS\Core\Imaging\IconRegistry;
use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;
use TYPO3\CMS\Extbase\Utility\ExtensionUtility;

(function (): void {
    // Register Extbase plugin (appears under "Plugins")
    ExtensionUtility::registerPlugin(
        'OnepageExtension',          // Extension name (no vendor needed)
        'OnepageRenderer',           // Plugin name
        'Onepage Renderer'           // BE label
    );

    // List type identifier generated by registerPlugin()
    $listType = 'onepageextension_onepagerenderer';

    // Register icon for the plugin
    $iconRegistry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(IconRegistry::class);
    $iconRegistry->registerIcon(
        'content-onepage-renderer',
        SvgIconProvider::class,
        ['source' => 'EXT:onepage_extension/Resources/Public/Icons/ce-onepage-renderer.svg']
    );

    // Map icon to tt_content type list + list_type
    $GLOBALS['TCA']['tt_content']['ctrl']['typeicon_classes']['list-' . $listType]
        = 'content-onepage-renderer';

    // New Content Element Wizard entry
    ExtensionManagementUtility::addPageTSConfig(
        '
mod.wizards.newContentElement.wizardItems.plugins {
  elements {
    onepagerenderer {
      iconIdentifier = content-onepage-renderer
      title = LLL:EXT:onepage_extension/Resources/Private/Language/locallang_db.xlf:plugin.onepage_renderer.title
      description = LLL:EXT:onepage_extension/Resources/Private/Language/locallang_db.xlf:plugin.onepage_renderer.description
      tt_content_defValues {
        CType = list
        list_type = ' . $listType . '
      }
    }
  }
  show := addToList(onepagerenderer)
}
        '
    );
})();
